/*
 *  CAPD 1 - Talent Registration
 *
 * This document contains the specification of the Talent Registration API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using IO.Swagger.Attributes;
using IO.Swagger.Models;
using Swashbuckle.Swagger.Annotations;

namespace IO.Swagger.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class AuthApiController : ControllerBase
    { 
        /// <summary>
        /// User Authorization
        /// </summary>
        /// <remarks>User Authorization</remarks>
        /// <param name="body">user auth</param>
        /// <response code="200">Success</response>
        /// <response code="400">Request had bad syntax or was impossible to fulfill.</response>
        /// <response code="401">Unauthorized. Missing valid authentication credentials for the target resource.</response>
        /// <response code="404">The specified resource was not found.</response>
        /// <response code="405">Invalid input</response>
        [HttpPost]
        [Route("/Auth/Login")]
        [ValidateModelState]
        [SwaggerOperation("Authuser")]
        [SwaggerResponse(statusCode: 200, type: typeof(LoginResponse), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Request had bad syntax or was impossible to fulfill.")]
        [SwaggerResponse(statusCode: 401, type: typeof(Error), description: "Unauthorized. Missing valid authentication credentials for the target resource.")]
        [SwaggerResponse(statusCode: 404, type: typeof(Error), description: "The specified resource was not found.")]
        public virtual IActionResult Authuser([FromBody]LoginRequest body)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(LoginResponse));

            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default(Error));

            //TODO: Uncomment the next line to return response 401 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(401, default(Error));

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404, default(Error));

            //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(405);
            string exampleJson = null;
            exampleJson = "{\n  \"firstName\" : \"abc\",\n  \"lastName\" : \"xyz\",\n  \"role\" : \"admin\",\n  \"userImage\" : \"data:image/png;base64,iVBORwKGK5CYII=\",\n  \"displayName\" : \"abc xyz\",\n  \"userId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\n  \"token\" : \"eyJhbGMDIyfQ.eyJzdWIiO.SflKx\"\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<LoginResponse>(exampleJson)
                        : default(LoginResponse);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
